// <auto-generated />
namespace MaridoDeAluguel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update231017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update231017));
        
        string IMigrationMetadata.Id
        {
            get { return "201710240135394_update-23-10-17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
